# Generated by Django 6.0 on 2025-12-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramstory',
            options={'verbose_name': 'Instagram Story', 'verbose_name_plural': 'Instagram Stories'},
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='stories/'),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='profile_pic_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagramstory',
            name='story_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
