# Generated by Django 6.0 on 2025-12-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_scraper', '0002_alter_instagramstory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='instagramuser',
            name='profile_pic_url',
        ),
        migrations.RemoveField(
            model_name='instagramuser',
            name='userid',
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
