# Generated by Django 6.0 on 2025-12-27 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_scraper', '0003_remove_instagramuser_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramstory',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='instagramstory',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='instagramuser',
            name='last_scraped',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
