# Generated by Django 6.0 on 2026-01-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_scraper', '0004_rename_user_instagramstory_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramstory',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='ai_caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='ai_hits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instagramstory',
            name='ai_is_interesting',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
